name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Echo Username (REMOVE THIS LATER)
      run: echo "Username is ${{ secrets.DOCKERHUB_USERNAME }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag basharherbawi/gsg-html:$(date +%s)
        docker push basharherbawi/gsg-html:$(date +%s)
